#!/usr/bin/python3
def safe_print_list(my_list=[], x=0):
    try:
        i = 0
        size = 0
        for i in range(0, x):
            print(my_list[i], end='')
            size += 1
        print("")
    except IndexError():
        size = 0
        for j in my_list:
            print(j, end='')
            size += 1
        print("")
    return size
